// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4f9KSYP0w3P9XEzMaFJV-J16NvJ2BtQ',
    appId: '1:753289904234:web:10011b40ccc6325455ca13',
    messagingSenderId: '753289904234',
    projectId: 'autoscan-d2ba8',
    authDomain: 'autoscan-d2ba8.firebaseapp.com',
    storageBucket: 'autoscan-d2ba8.firebasestorage.app',
    measurementId: 'G-0VEX8DV434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEi-NPSZ8EJIAbz2_lfxRM5Nvca-t04U',
    appId: '1:753289904234:android:7b8460bec0009d7e55ca13',
    messagingSenderId: '753289904234',
    projectId: 'autoscan-d2ba8',
    storageBucket: 'autoscan-d2ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD688SHPEbknKew9TNv6YzZYYsqvmTjHsY',
    appId: '1:753289904234:ios:a3c8fbe0b0820ade55ca13',
    messagingSenderId: '753289904234',
    projectId: 'autoscan-d2ba8',
    storageBucket: 'autoscan-d2ba8.firebasestorage.app',
    iosBundleId: 'com.example.autoScanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD688SHPEbknKew9TNv6YzZYYsqvmTjHsY',
    appId: '1:753289904234:ios:a3c8fbe0b0820ade55ca13',
    messagingSenderId: '753289904234',
    projectId: 'autoscan-d2ba8',
    storageBucket: 'autoscan-d2ba8.firebasestorage.app',
    iosBundleId: 'com.example.autoScanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI4f9KSYP0w3P9XEzMaFJV-J16NvJ2BtQ',
    appId: '1:753289904234:web:02135d02bbbe995755ca13',
    messagingSenderId: '753289904234',
    projectId: 'autoscan-d2ba8',
    authDomain: 'autoscan-d2ba8.firebaseapp.com',
    storageBucket: 'autoscan-d2ba8.firebasestorage.app',
    measurementId: 'G-3B8RLYLPV6',
  );
}